### ISSUE TITLE
GA_for_FJSP.py have a bug?

### ISSUE THREAD

**Issue by nbchengang** [Aihong-Sun/GA_for_FJSP#1]
Traceback (most recent call last):
  File "E:\JobShop\test\GA_for_FJSP.py", line 216, in <module>
    g.main(Processing_time,J,M_num,J_num,O_num)
  File "E:\JobShop\test\GA_for_FJSP.py", line 170, in main
    if best_fitness < Optimal_fit:
TypeError: '<' not supported between instances of 'list' and 'int'

**Comment by wobudaoa** [comment]
modify the line 'best_fitness = min(Fit)' into 'best_fitness = min(Fit)[0]'
